name: Call output test

on:
  workflow_dispatch
jobs:
  first-job:
    name: Test
    uses: NiedziolkaMichal/github-actions-test/.github/workflows/output-test.yml@main
    with: 
      publicationType: 'snapshot'
