name: Call output test

on:
  workflow_dispatch
jobs:
  first-job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: NiedziolkaMichal/github-actions-test/.github/workflows/output-test.yml@main
        with: 
           publicationType: 'snapshot'
