name: MongoDB Dump

permissions:
  contents: 'read'
  id-token: 'write'

on:
  workflow_dispatch
jobs:
  dump:
    name: MongoDB Dump
    runs-on: ubuntu-latest
    steps:
      - name: Auth GCloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCLOUD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}

      - name: Install mongodump
        shell: bash
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc |  gpg --dearmor | sudo tee /usr/share/keyrings/mongodb.gpg > /dev/null
          echo "deb [ arch=amd64 signed-by=/usr/share/keyrings/mongodb.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt update
          sudo apt install mongodb-database-tools
          mongodump --version

      - name: Dump database
        shell: bash
        run: mongodump --uri ${{ secrets.MONGO_BACKUP_URI }}

      - name: Generate destination name
        run: echo "NOW=$(date +'%Y-%m-%dT%H.%M.%S')" >> $GITHUB_ENV

      - name: Upload dump
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'dump'
          destination: fiszki_backup_${{ env.NOW }}
