name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    inputs:
      publicationType:
        type: string
        description: '"snapshot" or "beta" publication type which determines expiration date'
        default: "beta"
        required: false

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "My_Ref $My_Ref. First_Name $First_Name!"
        env:
          My_Ref: ${{ github.ref }}
          First_Name: ${{ inputs.publicationType == 'snapshot' && contains(fromJSON('["refs/heads/master", "refs/heads/main"]'), github.ref) && 'beta' || inputs.publicationType }}
