name: Reusable workflow

on:
  workflow_dispatch:
    # Map the workflow outputs to job outputs
    inputs:
      firstword:
        description: "The first output string"
        type: string

jobs:
  consecutiveness:
    runs-on: ubuntu-latest
    steps:
    - uses: mktcode/consecutive-workflow-action@eb43c6b5852dd0e33efa797a1817196d06daa4b2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    needs: [ consecutiveness ]
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=world" >> $GITHUB_OUTPUT
      - id: sleep
        run: sleep 30s
        shell: bash
      - id: step3
        run: echo "### asd ${{ inputs.firstword }}" >> $GITHUB_STEP_SUMMARY
